const audio=document.getElementById("audio"),listEl=document.getElementById("songList"),search=document.getElementById("search"),count=document.getElementById("count"),empty=document.getElementById("empty"),play=document.getElementById("play"),prev=document.getElementById("prev"),next=document.getElementById("next"),progress=document.getElementById("progress"),volume=document.getElementById("volume"),nowTitle=document.getElementById("nowTitle"),nowArtist=document.getElementById("nowArtist"),cover=document.getElementById("cover"),currentTime=document.getElementById("currentTime"),duration=document.getElementById("duration");
let songs=[],current=-1;
const fmt=s=>Number.isFinite(s)?`${Math.floor(s/60)}:${Math.floor(s%60).toString().padStart(2,"0")}`:"0:00";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function render(arr=songs){listEl.innerHTML="";count.textContent=`${arr.length} song${arr.length===1?"":"s"}`;empty.hidden=arr.length>0;arr.forEach(song=>{const i=songs.indexOf(song),card=document.createElement("article");card.className="song-card";card.innerHTML=`<img class="cover" src="${esc(song.cover||"assets/default-cover.svg")}" alt=""><div class="song-title">${esc(song.title)}</div><div class="artist">${esc(song.artist)}</div>`;card.onclick=()=>load(i,true);listEl.appendChild(card)})}
function load(i,auto=false){if(!songs[i])return;current=i;const s=songs[i];audio.src=s.src;nowTitle.textContent=s.title;nowArtist.textContent=s.artist;cover.src=s.cover||"assets/default-cover.svg";progress.value=0;if(auto)audio.play().catch(()=>{})}
play.onclick=()=>{if(current<0){if(songs.length)load(0,true);return}audio.paused?audio.play().catch(()=>{}):audio.pause()};
prev.onclick=()=>{if(songs.length)load((current-1+songs.length)%songs.length,true)};
next.onclick=()=>{if(songs.length)load((current+1)%songs.length,true)};
audio.onplay=()=>play.textContent="⏸";audio.onpause=()=>play.textContent="▶";audio.onloadedmetadata=()=>duration.textContent=fmt(audio.duration);audio.ontimeupdate=()=>{if(audio.duration)progress.value=audio.currentTime/audio.duration*100;currentTime.textContent=fmt(audio.currentTime)};audio.onended=()=>{if(songs.length)load((current+1)%songs.length,true)};
progress.oninput=()=>{if(audio.duration)audio.currentTime=progress.value/100*audio.duration};volume.oninput=()=>audio.volume=+volume.value;audio.volume=.8;
search.oninput=()=>{const q=search.value.toLowerCase().trim();render(songs.filter(s=>`${s.title} ${s.artist}`.toLowerCase().includes(q)))};
fetch("songs.json").then(r=>{if(!r.ok)throw Error("songs.json not found");return r.json()}).then(data=>{songs=Array.isArray(data)?data:data.songs||[];render()}).catch(()=>{songs=[];render();empty.hidden=false;empty.textContent="Add songs to songs.json to start playing."});
